name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - src/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: daily-coding-problem-bot
          heroku_email: idobetakashi@gmail.com
